import * as fs from 'fs';
import * as path from 'path';
import type { ServiceContract } from '../contracts.js';
import { collectProxyEntries, type ProxyEntry } from './proxy-entries.js';

const GENERATED_HEADER = '# Generated by composable.env — DO NOT EDIT';

export interface CaddyfileWriteResult {
  filePath: string;
  warnings: string[];
}

/**
 * Generate Caddyfile content from proxy entries for a specific profile.
 *
 * Output is intentionally minimal — one site block per hostname,
 * with reverse_proxy pointing at the container's Docker DNS name.
 * Caddy's automatic HTTPS (via its internal CA on .local hosts, or
 * Let's Encrypt elsewhere) handles certs without extra config.
 */
function generateCaddyfile(
  entries: ProxyEntry[],
  domain: string,
  profileName: string,
): string {
  const lines: string[] = [
    GENERATED_HEADER,
    `# Profile: ${profileName}`,
    ``,
  ];

  for (const entry of entries) {
    const hostname = `${entry.subdomain}.${domain}`;
    // Site block — Caddy auto-issues a cert (internal CA on .local,
    // Let's Encrypt otherwise). reverse_proxy handles WebSockets natively
    // and re-resolves Docker DNS per request, so container restarts
    // don't leave a stale cached IP.
    lines.push(
      `${hostname} {`,
      `\treverse_proxy ${entry.serviceName}:${entry.port}`,
      `}`,
      ``,
    );
  }

  return lines.join('\n');
}

/**
 * Write Caddyfile config files — one per profile that has a domain configured.
 * Files are written next to the compose file. Output file naming mirrors
 * the nginx emitter: `Caddyfile` for single-profile builds, `Caddyfile.{profile}`
 * when multiple profiles emit caddyfiles.
 */
export function writeCaddyfiles(
  projectRoot: string,
  contracts: Map<string, ServiceContract>,
  profileNames: string[],
  profileSuffixes: Record<string, string>,
  profileDomains: Record<string, string>,
): CaddyfileWriteResult[] {
  const results: CaddyfileWriteResult[] = [];

  // Count how many profiles will actually emit, so we know whether to
  // use a suffixed filename. (Mirrors the nginx behavior.)
  const emittingProfiles = profileNames.filter(p => {
    const domain = profileDomains[p];
    if (!domain) return false;
    const suffix = profileSuffixes[p] || '';
    return collectProxyEntries(contracts, suffix).length > 0;
  });

  for (const profileName of profileNames) {
    const suffix = profileSuffixes[profileName] || '';
    const domain = profileDomains[profileName] || '';

    if (!domain) continue; // No domain configured, skip caddy for this profile

    const entries = collectProxyEntries(contracts, suffix);
    if (entries.length === 0) continue;

    const content = generateCaddyfile(entries, domain, profileName);
    const fileName = emittingProfiles.length === 1
      ? 'Caddyfile'
      : `Caddyfile.${profileName}`;
    const filePath = path.join(projectRoot, fileName);

    fs.writeFileSync(filePath, content, 'utf8');

    // Auto-gitignore the generated file
    const gitignorePath = path.join(projectRoot, '.gitignore');
    if (fs.existsSync(gitignorePath)) {
      const gitignore = fs.readFileSync(gitignorePath, 'utf8');
      if (!gitignore.includes(fileName)) {
        fs.appendFileSync(gitignorePath, `\n${fileName}\n`);
      }
    }

    results.push({
      filePath,
      warnings: entries.map(e => `  ${e.subdomain}.${domain} → ${e.serviceName}:${e.port}`),
    });
  }

  return results;
}
