import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';
import { execSync } from 'child_process';

const GENERATED_HEADER = '# Generated by composable.env — DO NOT EDIT';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ComposeServiceEntry {
  contractName: string;
  serviceName: string;
  vars: Record<string, string>;
  config?: Record<string, unknown>;
}

export interface ComposeWriteResult {
  filePath: string;
  warnings: string[];
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Write a complete docker-compose.yml from a batch of service entries.
 *
 * This replaces the old incremental approach — all entries targeting the same
 * file are collected first, then written in a single pass. This enables:
 * - Var collision detection across contracts
 * - Top-level volumes/networks auto-detection
 * - Proper overwrite-vs-error semantics
 */
export async function writeDockerComposeFile(
  filePath: string,
  entries: ComposeServiceEntry[],
  profileName?: string
): Promise<ComposeWriteResult> {
  const warnings: string[] = [];

  // ── Guard: refuse to overwrite a non-generated file ──
  if (fs.existsSync(filePath)) {
    const existing = await fs.promises.readFile(filePath, 'utf8');
    if (!existing.startsWith(GENERATED_HEADER)) {
      throw new Error(
        `${filePath} exists but was not generated by composable.env. ` +
        `Delete or rename it before building.`
      );
    }
  }

  // ── Build the compose document from scratch ──
  const services: Record<string, Record<string, unknown>> = {};

  // Track var origins for collision detection
  const varOrigins: Record<string, Record<string, { value: string; contract: string }>> = {};

  for (const entry of entries) {
    const { contractName, serviceName, vars, config } = entry;

    if (!services[serviceName]) {
      services[serviceName] = {};
    }

    // Merge service config (image, ports, volumes, etc.)
    if (config) {
      for (const [key, value] of Object.entries(config)) {
        if (key === 'environment') continue; // managed via vars
        const existing = services[serviceName][key];

        if (Array.isArray(value) && Array.isArray(existing)) {
          const merged = [...existing, ...value];
          services[serviceName][key] = [...new Set(merged.map(String))];
        } else if (
          value && typeof value === 'object' && !Array.isArray(value) &&
          existing && typeof existing === 'object' && !Array.isArray(existing)
        ) {
          services[serviceName][key] = {
            ...(existing as Record<string, unknown>),
            ...(value as Record<string, unknown>),
          };
        } else {
          services[serviceName][key] = value;
        }
      }
    }

    // Track vars for collision detection before merging
    if (!varOrigins[serviceName]) varOrigins[serviceName] = {};
    for (const [key, value] of Object.entries(vars)) {
      const existing = varOrigins[serviceName][key];
      if (existing && existing.value !== value) {
        warnings.push(
          `⚠️ Conflict: ${key} set by both [${existing.contract}] and [${contractName}] ` +
          `with different values on service '${serviceName}'`
        );
      }
      varOrigins[serviceName][key] = { value, contract: contractName };
    }

    // Merge vars into environment
    const env = (services[serviceName].environment || {}) as Record<string, string>;
    for (const [key, value] of Object.entries(vars)) {
      env[key] = String(value);
    }
    if (Object.keys(env).length > 0) {
      services[serviceName].environment = env;
    }
  }

  // ── Auto-detect top-level volumes ──
  const namedVolumes = detectNamedVolumes(services);
  const namedNetworks = detectNamedNetworks(services);

  const doc: Record<string, unknown> = { services };
  if (namedVolumes.length > 0) {
    const volumes: Record<string, null> = {};
    for (const v of namedVolumes) volumes[v] = null;
    doc.volumes = volumes;
  }
  if (namedNetworks.length > 0) {
    const networks: Record<string, null> = {};
    for (const n of namedNetworks) networks[n] = null;
    doc.networks = networks;
  }

  // ── Write ──
  const dir = path.dirname(filePath);
  if (dir !== '.' && !fs.existsSync(dir)) {
    await fs.promises.mkdir(dir, { recursive: true });
  }

  const header = [
    GENERATED_HEADER,
    profileName
      ? `# Profile: ${profileName} | Built: ${new Date().toISOString()}`
      : `# Built: ${new Date().toISOString()}`,
    '',
  ].join('\n');

  const yamlStr = yaml.stringify(doc, { lineWidth: 0 });
  await fs.promises.writeFile(filePath, header + yamlStr, 'utf8');

  // ── Auto-gitignore ──
  const gitignoreWarnings = await ensureGitignored(filePath);
  warnings.push(...gitignoreWarnings);

  return { filePath, warnings };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Detect named volumes from service volume mounts.
 * Named volumes are `name:/path` where name doesn't start with . or /
 */
function detectNamedVolumes(services: Record<string, Record<string, unknown>>): string[] {
  const names = new Set<string>();
  for (const service of Object.values(services)) {
    const volumes = service.volumes;
    if (!Array.isArray(volumes)) continue;
    for (const vol of volumes) {
      const str = String(vol);
      const colonIdx = str.indexOf(':');
      if (colonIdx === -1) continue;
      const source = str.slice(0, colonIdx);
      // Named volume: doesn't start with . / ~ or contain path separators before the colon
      if (source && !source.startsWith('.') && !source.startsWith('/') && !source.startsWith('~')) {
        names.add(source);
      }
    }
  }
  return [...names].sort();
}

/**
 * Detect named networks from service network references.
 */
function detectNamedNetworks(services: Record<string, Record<string, unknown>>): string[] {
  const names = new Set<string>();
  for (const service of Object.values(services)) {
    const networks = service.networks;
    if (Array.isArray(networks)) {
      for (const n of networks) names.add(String(n));
    } else if (networks && typeof networks === 'object') {
      for (const n of Object.keys(networks as Record<string, unknown>)) names.add(n);
    }
  }
  return [...names].sort();
}

/**
 * Ensure the compose file is in .gitignore. Returns warnings if the file
 * is already tracked by git.
 */
async function ensureGitignored(filePath: string): Promise<string[]> {
  const warnings: string[] = [];
  const projectRoot = findGitRoot(filePath);
  if (!projectRoot) return warnings;

  const relativePath = path.relative(projectRoot, path.resolve(filePath));
  const gitignorePath = path.join(projectRoot, '.gitignore');

  // Check if already tracked by git
  try {
    execSync(`git ls-files --error-unmatch "${relativePath}"`, {
      cwd: projectRoot,
      stdio: 'pipe',
    });
    // If the command succeeds, the file IS tracked
    warnings.push(
      `⚠️ ${relativePath} is already tracked by git and contains secrets! ` +
      `Run: git rm --cached "${relativePath}" to untrack it.`
    );
  } catch {
    // Not tracked — good
  }

  // Check .gitignore for the entry
  let gitignoreContent = '';
  if (fs.existsSync(gitignorePath)) {
    gitignoreContent = await fs.promises.readFile(gitignorePath, 'utf8');
  }

  // Check if the file (or its basename) is already ignored
  const basename = path.basename(filePath);
  const lines = gitignoreContent.split('\n').map(l => l.trim());
  const alreadyIgnored = lines.some(
    line => line === relativePath || line === basename || line === `/${relativePath}`
  );

  if (!alreadyIgnored) {
    const entry = relativePath;
    const newContent = gitignoreContent.endsWith('\n') || gitignoreContent === ''
      ? gitignoreContent
      : gitignoreContent + '\n';
    await fs.promises.writeFile(
      gitignorePath,
      newContent + `# Generated by composable.env (contains secrets)\n${entry}\n`,
      'utf8'
    );
  }

  return warnings;
}

/**
 * Walk up from a file path to find the git root.
 */
function findGitRoot(fromPath: string): string | null {
  let dir = path.resolve(path.dirname(fromPath));
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, '.git'))) return dir;
    dir = path.dirname(dir);
  }
  return null;
}

// ─── Legacy single-service API (kept for backwards compat) ────────────────────

/**
 * @deprecated Use writeDockerComposeFile() with batched entries instead.
 */
export async function writeDockerComposeService(
  filePath: string,
  serviceName: string,
  vars: Record<string, string>,
  config?: Record<string, unknown>,
  profileName?: string
): Promise<void> {
  await writeDockerComposeFile(filePath, [{
    contractName: serviceName,
    serviceName,
    vars,
    config,
  }], profileName);
}
