import * as fs from 'fs';
import * as path from 'path';
import { Document, Pair, Scalar, YAMLMap, Alias, stringify } from 'yaml';
import { execSync } from 'child_process';

const GENERATED_HEADER = '# Generated by composable.env — DO NOT EDIT';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ComposeServiceEntry {
  contractName: string;
  serviceName: string;
  vars: Record<string, string>;
  config?: Record<string, unknown>;
}

export interface ComposeMultiProfileEntry extends ComposeServiceEntry {
  profileName: string;
}

export interface ComposeWriteResult {
  filePath: string;
  warnings: string[];
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Write a multi-profile docker-compose.yml from entries across all profiles.
 *
 * For each target service:
 * - If the service has identical environment across all profiles → single entry, no profiles: key
 * - If the service varies → shared config in x-{service} anchor, per-profile variants with <<: *merge
 *
 * Uses YAML 1.1 merge keys (<<:) which Docker Compose explicitly supports.
 */
export async function writeMultiProfileComposeFile(
  filePath: string,
  entries: ComposeMultiProfileEntry[],
  profileNames: string[]
): Promise<ComposeWriteResult> {
  const warnings: string[] = [];

  // ── Guard: refuse to overwrite a non-generated file ──
  if (fs.existsSync(filePath)) {
    const existing = await fs.promises.readFile(filePath, 'utf8');
    if (!existing.startsWith(GENERATED_HEADER)) {
      throw new Error(
        `${filePath} exists but was not generated by composable.env. ` +
        `Delete or rename it before building.`
      );
    }
  }

  // ── Group entries by target service, then by profile ──
  // serviceData[serviceName][profileName] = { mergedConfig, mergedVars }
  const serviceData = new Map<string, Map<string, {
    config: Record<string, unknown>;
    vars: Record<string, string>;
  }>>();

  // Track var origins for collision detection (per profile)
  const varOrigins = new Map<string, Map<string, Map<string, { value: string; contract: string }>>>();

  for (const entry of entries) {
    const { contractName, serviceName, profileName, vars, config } = entry;

    if (!serviceData.has(serviceName)) {
      serviceData.set(serviceName, new Map());
    }
    const profileMap = serviceData.get(serviceName)!;

    if (!profileMap.has(profileName)) {
      profileMap.set(profileName, { config: {}, vars: {} });
    }
    const data = profileMap.get(profileName)!;

    // Merge config
    if (config) {
      for (const [key, value] of Object.entries(config)) {
        if (key === 'environment') continue;
        if (key === 'container_name') continue; // excluded — would conflict across profiles
        const existing = data.config[key];

        if (Array.isArray(value) && Array.isArray(existing)) {
          data.config[key] = [...new Set([...existing, ...value].map(String))];
        } else if (
          value && typeof value === 'object' && !Array.isArray(value) &&
          existing && typeof existing === 'object' && !Array.isArray(existing)
        ) {
          data.config[key] = { ...(existing as Record<string, unknown>), ...(value as Record<string, unknown>) };
        } else {
          data.config[key] = value;
        }
      }
    }

    // Track collision detection
    if (!varOrigins.has(serviceName)) varOrigins.set(serviceName, new Map());
    if (!varOrigins.get(serviceName)!.has(profileName)) varOrigins.get(serviceName)!.set(profileName, new Map());
    const origins = varOrigins.get(serviceName)!.get(profileName)!;

    for (const [key, value] of Object.entries(vars)) {
      const existing = origins.get(key);
      if (existing && existing.value !== value) {
        warnings.push(
          `⚠️ Conflict: ${key} set by both [${existing.contract}] and [${contractName}] ` +
          `with different values on service '${serviceName}' (profile: ${profileName})`
        );
      }
      origins.set(key, { value, contract: contractName });
    }

    // Merge vars
    Object.assign(data.vars, vars);
  }

  // ── Build the YAML Document with anchors ──
  const doc = new Document({});
  doc.setSchema('1.1'); // enables merge key support

  const docContents = doc.contents as YAMLMap;

  // Collect all services (flat) for volume/network detection later
  const allServicesFlat: Record<string, Record<string, unknown>> = {};

  // ── First pass: determine which services are directly profiled (varying env) ──
  const profiledServices = new Set<string>();
  for (const [serviceName, profileMap] of serviceData) {
    const profiles = [...profileMap.keys()];
    if (profiles.length > 1 && !allProfilesIdentical(profileMap)) {
      profiledServices.add(serviceName);
    }
  }

  // ── Propagate profiling through depends_on (contagious) ──
  // If service A depends on profiled service B, A must also become profiled.
  // Repeat until stable — profiling is transitive.
  let changed = true;
  while (changed) {
    changed = false;
    for (const [serviceName, profileMap] of serviceData) {
      if (profiledServices.has(serviceName)) continue;

      // Check if any profile's config has depends_on referencing a profiled service
      for (const [, data] of profileMap) {
        if (dependsOnProfiledService(data.config.depends_on, profiledServices)) {
          profiledServices.add(serviceName);
          changed = true;
          break;
        }
      }
    }
  }

  // ── Second pass: emit services, rewriting depends_on for profiled refs ──
  for (const [serviceName, profileMap] of serviceData) {
    const profiles = [...profileMap.keys()];
    const isProfiled = profiledServices.has(serviceName);

    if (!isProfiled) {
      // Single profile or identical across profiles — emit once, no profiles: key
      const firstProfile = profiles[0];
      const data = profileMap.get(firstProfile)!;
      const serviceObj: Record<string, unknown> = { ...data.config };
      if (Object.keys(data.vars).length > 0) {
        serviceObj.environment = { ...data.vars };
      }

      allServicesFlat[serviceName] = serviceObj;

      const serviceNode = doc.createNode(serviceObj);
      addToServices(docContents, serviceName, serviceNode);
    } else {
      // Varying env across profiles — use x- anchor for shared config
      const sharedConfig = extractSharedConfig(profileMap);

      // Remove depends_on from shared config — it needs per-profile rewriting
      const sharedHasDependsOn = 'depends_on' in sharedConfig;
      const sharedDependsOn = sharedConfig.depends_on;
      if (sharedHasDependsOn) {
        delete sharedConfig.depends_on;
      }

      const anchorName = `${serviceName}-base`;

      // Create the x- extension node with anchor
      if (Object.keys(sharedConfig).length > 0) {
        const anchorNode = doc.createNode(sharedConfig) as YAMLMap;
        anchorNode.anchor = anchorName;
        const extensionKey = `x-${serviceName}`;
        docContents.add(doc.createPair(extensionKey, anchorNode));
      }

      // Create per-profile service variants
      for (const profileName of profiles) {
        const data = profileMap.get(profileName)!;
        const variantName = `${serviceName}-${profileName}`;

        const variantNode = new YAMLMap();

        // Add <<: *anchor merge if we have shared config
        if (Object.keys(sharedConfig).length > 0) {
          const mergeKey = new Scalar('<<');
          (mergeKey as Scalar).type = Scalar.PLAIN;
          const aliasNode = new Alias(anchorName);
          variantNode.add(new Pair(mergeKey, aliasNode));
        }

        // Add profiles: [profileName]
        variantNode.add(doc.createPair('profiles', doc.createNode([profileName])));

        // Add depends_on with profiled service name rewriting
        const rawDependsOn = data.config.depends_on ?? sharedDependsOn;
        if (rawDependsOn) {
          const rewritten = rewriteDependsOn(rawDependsOn, profiledServices, profileName);
          variantNode.add(doc.createPair('depends_on', doc.createNode(rewritten)));
        }

        // Add per-profile config that differs from shared (excluding depends_on, already handled)
        const perProfileConfig = getPerProfileConfig(data.config, sharedConfig);
        delete perProfileConfig.depends_on;
        for (const [key, value] of Object.entries(perProfileConfig)) {
          variantNode.add(doc.createPair(key, doc.createNode(value)));
        }

        // Add environment
        if (Object.keys(data.vars).length > 0) {
          variantNode.add(doc.createPair('environment', doc.createNode(data.vars)));
        }

        // Track for volume/network detection
        allServicesFlat[variantName] = { ...data.config, environment: data.vars };

        addToServices(docContents, variantName, variantNode);
      }
    }
  }

  // ── Auto-detect top-level volumes and networks ──
  const namedVolumes = detectNamedVolumes(allServicesFlat);
  const namedNetworks = detectNamedNetworks(allServicesFlat);

  if (namedVolumes.length > 0) {
    const volumes: Record<string, null> = {};
    for (const v of namedVolumes) volumes[v] = null;
    docContents.add(doc.createPair('volumes', doc.createNode(volumes)));
  }
  if (namedNetworks.length > 0) {
    const networks: Record<string, null> = {};
    for (const n of namedNetworks) networks[n] = null;
    docContents.add(doc.createPair('networks', doc.createNode(networks)));
  }

  // ── Write ──
  const dir = path.dirname(filePath);
  if (dir !== '.' && !fs.existsSync(dir)) {
    await fs.promises.mkdir(dir, { recursive: true });
  }

  const header = [
    GENERATED_HEADER,
    `# Profiles: ${profileNames.join(', ')} | Built: ${new Date().toISOString()}`,
    '',
  ].join('\n');

  const yamlStr = doc.toString({ lineWidth: 0 });
  await fs.promises.writeFile(filePath, header + yamlStr, 'utf8');

  // ── Auto-gitignore ──
  const gitignoreWarnings = await ensureGitignored(filePath);
  warnings.push(...gitignoreWarnings);

  return { filePath, warnings };
}

/**
 * Write a single-profile docker-compose.yml from a batch of service entries.
 * Kept for backwards compatibility — multi-profile is now the primary path.
 */
export async function writeDockerComposeFile(
  filePath: string,
  entries: ComposeServiceEntry[],
  profileName?: string
): Promise<ComposeWriteResult> {
  const warnings: string[] = [];

  if (fs.existsSync(filePath)) {
    const existing = await fs.promises.readFile(filePath, 'utf8');
    if (!existing.startsWith(GENERATED_HEADER)) {
      throw new Error(
        `${filePath} exists but was not generated by composable.env. ` +
        `Delete or rename it before building.`
      );
    }
  }

  const services: Record<string, Record<string, unknown>> = {};
  const varOrigins: Record<string, Record<string, { value: string; contract: string }>> = {};

  for (const entry of entries) {
    const { contractName, serviceName, vars, config } = entry;

    if (!services[serviceName]) {
      services[serviceName] = {};
    }

    if (config) {
      for (const [key, value] of Object.entries(config)) {
        if (key === 'environment') continue;
        const existing = services[serviceName][key];

        if (Array.isArray(value) && Array.isArray(existing)) {
          services[serviceName][key] = [...new Set([...existing, ...value].map(String))];
        } else if (
          value && typeof value === 'object' && !Array.isArray(value) &&
          existing && typeof existing === 'object' && !Array.isArray(existing)
        ) {
          services[serviceName][key] = { ...(existing as Record<string, unknown>), ...(value as Record<string, unknown>) };
        } else {
          services[serviceName][key] = value;
        }
      }
    }

    if (!varOrigins[serviceName]) varOrigins[serviceName] = {};
    for (const [key, value] of Object.entries(vars)) {
      const existing = varOrigins[serviceName][key];
      if (existing && existing.value !== value) {
        warnings.push(
          `⚠️ Conflict: ${key} set by both [${existing.contract}] and [${contractName}] ` +
          `with different values on service '${serviceName}'`
        );
      }
      varOrigins[serviceName][key] = { value, contract: contractName };
    }

    const env = (services[serviceName].environment || {}) as Record<string, string>;
    for (const [key, value] of Object.entries(vars)) {
      env[key] = String(value);
    }
    if (Object.keys(env).length > 0) {
      services[serviceName].environment = env;
    }
  }

  const namedVolumes = detectNamedVolumes(services);
  const namedNetworks = detectNamedNetworks(services);

  const doc: Record<string, unknown> = { services };
  if (namedVolumes.length > 0) {
    const volumes: Record<string, null> = {};
    for (const v of namedVolumes) volumes[v] = null;
    doc.volumes = volumes;
  }
  if (namedNetworks.length > 0) {
    const networks: Record<string, null> = {};
    for (const n of namedNetworks) networks[n] = null;
    doc.networks = networks;
  }

  const dir = path.dirname(filePath);
  if (dir !== '.' && !fs.existsSync(dir)) {
    await fs.promises.mkdir(dir, { recursive: true });
  }

  const header = [
    GENERATED_HEADER,
    profileName
      ? `# Profile: ${profileName} | Built: ${new Date().toISOString()}`
      : `# Built: ${new Date().toISOString()}`,
    '',
  ].join('\n');

  const yamlStr = stringify(doc, { lineWidth: 0 });
  await fs.promises.writeFile(filePath, header + yamlStr, 'utf8');

  const gitignoreWarnings = await ensureGitignored(filePath);
  warnings.push(...gitignoreWarnings);

  return { filePath, warnings };
}

// ─── Multi-profile helpers ────────────────────────────────────────────────────

/**
 * Ensure the 'services' key exists on the document root and add a service to it.
 */
function addToServices(docContents: YAMLMap, name: string, node: unknown): void {
  let servicesNode = docContents.get('services', true) as YAMLMap | undefined;
  if (!servicesNode) {
    servicesNode = new YAMLMap();
    // Insert services after any x- extension keys
    docContents.add(new Pair(new Scalar('services'), servicesNode));
  }
  servicesNode.add(new Pair(new Scalar(name), node));
}

/**
 * Check if a depends_on value references any profiled service.
 */
function dependsOnProfiledService(
  dependsOn: unknown,
  profiledServices: Set<string>
): boolean {
  if (!dependsOn) return false;
  if (Array.isArray(dependsOn)) {
    return dependsOn.some(dep => profiledServices.has(String(dep)));
  }
  if (typeof dependsOn === 'object') {
    return Object.keys(dependsOn as Record<string, unknown>).some(name => profiledServices.has(name));
  }
  return false;
}

/**
 * Rewrite depends_on references: if a dependency is a profiled service,
 * replace it with the profile-suffixed variant name.
 *
 * Supports both array format: ["redis", "numero"]
 * and object format: { "numero": { "condition": "service_healthy" } }
 */
function rewriteDependsOn(
  dependsOn: unknown,
  profiledServices: Set<string>,
  profileName: string
): unknown {
  if (Array.isArray(dependsOn)) {
    return dependsOn.map(dep => {
      const name = String(dep);
      return profiledServices.has(name) ? `${name}-${profileName}` : name;
    });
  }
  if (dependsOn && typeof dependsOn === 'object') {
    const result: Record<string, unknown> = {};
    for (const [name, value] of Object.entries(dependsOn as Record<string, unknown>)) {
      const key = profiledServices.has(name) ? `${name}-${profileName}` : name;
      result[key] = value;
    }
    return result;
  }
  return dependsOn;
}

/**
 * Check if all profiles for a service produce identical environment vars.
 */
function allProfilesIdentical(
  profileMap: Map<string, { config: Record<string, unknown>; vars: Record<string, string> }>
): boolean {
  const profiles = [...profileMap.values()];
  if (profiles.length <= 1) return true;

  const firstVars = JSON.stringify(sortedEntries(profiles[0].vars));
  for (let i = 1; i < profiles.length; i++) {
    if (JSON.stringify(sortedEntries(profiles[i].vars)) !== firstVars) return false;
  }
  return true;
}

/**
 * Extract config keys that are identical across all profiles.
 * These go into the x- anchor block.
 */
function extractSharedConfig(
  profileMap: Map<string, { config: Record<string, unknown>; vars: Record<string, string> }>
): Record<string, unknown> {
  const profiles = [...profileMap.values()];
  if (profiles.length === 0) return {};

  const shared: Record<string, unknown> = {};
  const firstConfig = profiles[0].config;

  for (const [key, value] of Object.entries(firstConfig)) {
    const serialized = JSON.stringify(value);
    const allSame = profiles.every(p => JSON.stringify(p.config[key]) === serialized);
    if (allSame) {
      shared[key] = value;
    }
  }

  return shared;
}

/**
 * Get config keys that differ from the shared config (per-profile overrides).
 */
function getPerProfileConfig(
  config: Record<string, unknown>,
  sharedConfig: Record<string, unknown>
): Record<string, unknown> {
  const perProfile: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(config)) {
    if (!(key in sharedConfig)) {
      perProfile[key] = value;
    }
  }
  return perProfile;
}

function sortedEntries(obj: Record<string, string>): [string, string][] {
  return Object.entries(obj).sort(([a], [b]) => a.localeCompare(b));
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

function detectNamedVolumes(services: Record<string, Record<string, unknown>>): string[] {
  const names = new Set<string>();
  for (const service of Object.values(services)) {
    const volumes = service.volumes;
    if (!Array.isArray(volumes)) continue;
    for (const vol of volumes) {
      const str = String(vol);
      const colonIdx = str.indexOf(':');
      if (colonIdx === -1) continue;
      const source = str.slice(0, colonIdx);
      if (source && !source.startsWith('.') && !source.startsWith('/') && !source.startsWith('~') && !source.startsWith('$')) {
        names.add(source);
      }
    }
  }
  return [...names].sort();
}

function detectNamedNetworks(services: Record<string, Record<string, unknown>>): string[] {
  const names = new Set<string>();
  for (const service of Object.values(services)) {
    const networks = service.networks;
    if (Array.isArray(networks)) {
      for (const n of networks) names.add(String(n));
    } else if (networks && typeof networks === 'object') {
      for (const n of Object.keys(networks as Record<string, unknown>)) names.add(n);
    }
  }
  return [...names].sort();
}

async function ensureGitignored(filePath: string): Promise<string[]> {
  const warnings: string[] = [];
  const projectRoot = findGitRoot(filePath);
  if (!projectRoot) return warnings;

  const relativePath = path.relative(projectRoot, path.resolve(filePath));
  const gitignorePath = path.join(projectRoot, '.gitignore');

  try {
    execSync(`git ls-files --error-unmatch "${relativePath}"`, {
      cwd: projectRoot,
      stdio: 'pipe',
    });
    warnings.push(
      `⚠️ ${relativePath} is already tracked by git and contains secrets! ` +
      `Run: git rm --cached "${relativePath}" to untrack it.`
    );
  } catch {
    // Not tracked — good
  }

  let gitignoreContent = '';
  if (fs.existsSync(gitignorePath)) {
    gitignoreContent = await fs.promises.readFile(gitignorePath, 'utf8');
  }

  const basename = path.basename(filePath);
  const lines = gitignoreContent.split('\n').map(l => l.trim());
  const alreadyIgnored = lines.some(
    line => line === relativePath || line === basename || line === `/${relativePath}`
  );

  if (!alreadyIgnored) {
    const entry = relativePath;
    const newContent = gitignoreContent.endsWith('\n') || gitignoreContent === ''
      ? gitignoreContent
      : gitignoreContent + '\n';
    await fs.promises.writeFile(
      gitignorePath,
      newContent + `# Generated by composable.env (contains secrets)\n${entry}\n`,
      'utf8'
    );
  }

  return warnings;
}

function findGitRoot(fromPath: string): string | null {
  let dir = path.resolve(path.dirname(fromPath));
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, '.git'))) return dir;
    dir = path.dirname(dir);
  }
  return null;
}

// ─── Legacy single-service API ────────────────────────────────────────────────

/**
 * @deprecated Use writeMultiProfileComposeFile() or writeDockerComposeFile() instead.
 */
export async function writeDockerComposeService(
  filePath: string,
  serviceName: string,
  vars: Record<string, string>,
  config?: Record<string, unknown>,
  profileName?: string
): Promise<void> {
  await writeDockerComposeFile(filePath, [{
    contractName: serviceName,
    serviceName,
    vars,
    config,
  }], profileName);
}
