import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';

/**
 * Write a service's config and resolved environment variables into a
 * docker-compose.yml. The entire compose file is a build artifact —
 * fully generated by ce build from contracts.
 *
 * - `config` (image, ports, volumes, etc.) is merged into the service definition
 * - `vars` are merged into the service's `environment:` block
 * - Multiple contracts can target the same service — both config and vars are additive
 * - If the file or service doesn't exist, it's created
 */
export async function writeDockerComposeService(
  filePath: string,
  serviceName: string,
  vars: Record<string, string>,
  config?: Record<string, unknown>,
  profileName?: string
): Promise<void> {
  let doc: Record<string, unknown>;

  if (fs.existsSync(filePath)) {
    const content = await fs.promises.readFile(filePath, 'utf8');
    doc = (yaml.parse(content) as Record<string, unknown>) || {};
  } else {
    doc = {};
  }

  // Ensure services key exists
  if (!doc.services || typeof doc.services !== 'object') {
    doc.services = {};
  }

  const services = doc.services as Record<string, Record<string, unknown>>;

  // Ensure the target service exists
  if (!services[serviceName]) {
    services[serviceName] = {};
  }

  // Merge service config (image, ports, volumes, etc.)
  // Arrays (ports, volumes, depends_on) are concatenated and deduped
  // Objects are deep-merged
  // Scalars are overwritten (last contract wins)
  if (config) {
    for (const [key, value] of Object.entries(config)) {
      if (key === 'environment') continue; // environment is managed via vars
      const existing = services[serviceName][key];

      if (Array.isArray(value) && Array.isArray(existing)) {
        // Concatenate and dedupe arrays
        const merged = [...existing, ...value];
        services[serviceName][key] = [...new Set(merged.map(String))];
      } else if (
        value && typeof value === 'object' && !Array.isArray(value) &&
        existing && typeof existing === 'object' && !Array.isArray(existing)
      ) {
        // Deep merge objects
        services[serviceName][key] = { ...(existing as Record<string, unknown>), ...(value as Record<string, unknown>) };
      } else {
        services[serviceName][key] = value;
      }
    }
  }

  // Merge vars into environment (additive — multiple contracts
  // can target the same service, each appending their vars)
  const existingEnv = (services[serviceName].environment || {}) as Record<string, string>;
  for (const [key, value] of Object.entries(vars)) {
    existingEnv[key] = String(value);
  }
  if (Object.keys(existingEnv).length > 0) {
    services[serviceName].environment = existingEnv;
  }

  // Ensure output directory exists
  const dir = path.dirname(filePath);
  if (dir !== '.' && !fs.existsSync(dir)) {
    await fs.promises.mkdir(dir, { recursive: true });
  }

  // Write with a header comment
  const header = [
    '# Generated by composable.env — DO NOT EDIT',
    profileName ? `# Profile: ${profileName} | Built: ${new Date().toISOString()}` : `# Built: ${new Date().toISOString()}`,
    '',
  ].join('\n');

  const yamlStr = yaml.stringify(doc, { lineWidth: 0 });
  await fs.promises.writeFile(filePath, header + yamlStr, 'utf8');
}
