import * as fs from 'fs';
import * as path from 'path';
import type { ServiceContract } from '../contracts.js';

const GENERATED_HEADER = '# Generated by composable.env — DO NOT EDIT';

export interface NginxServiceEntry {
  subdomain: string;
  serviceName: string;    // profiled service name (e.g., "portainer-local")
  port: number;
}

export interface NginxWriteResult {
  filePath: string;
  warnings: string[];
}

/**
 * Extract the first container port from a Docker Compose ports array.
 * Handles formats: "9000:9000", "9000:9000/tcp", "127.0.0.1:9000:9000"
 * Returns the container-side port (right side of the colon).
 */
function extractPort(ports: unknown[]): number | null {
  for (const p of ports) {
    const str = String(p);
    // Remove protocol suffix
    const clean = str.replace(/\/(tcp|udp)$/, '');
    const parts = clean.split(':');
    // Last part is always the container port
    const containerPort = parseInt(parts[parts.length - 1], 10);
    if (!isNaN(containerPort)) return containerPort;
  }
  return null;
}

/**
 * Collect nginx entries from contracts that have subdomain + target.
 * Uses profiled service names and the profile domain.
 */
export function collectNginxEntries(
  contracts: Map<string, ServiceContract>,
  profileName: string,
  profileSuffix: string,
  profileDomain: string,
): NginxServiceEntry[] {
  const entries: NginxServiceEntry[] = [];

  for (const [, contract] of contracts) {
    if (!contract.target?.subdomain) continue;

    const config = contract.target.config || {};
    const ports = config.ports as unknown[] | undefined;

    if (!ports || ports.length === 0) continue;

    const port = extractPort(ports);
    if (!port) continue;

    const serviceName = `${contract.target.service}${profileSuffix}`;

    entries.push({
      subdomain: contract.target.subdomain,
      serviceName,
      port,
    });
  }

  return entries;
}

/**
 * Generate nginx config content from entries for a specific profile.
 */
function generateNginxConfig(
  entries: NginxServiceEntry[],
  domain: string,
  profileName: string,
): string {
  const lines: string[] = [
    GENERATED_HEADER,
    `# Profile: ${profileName}`,
    '',
  ];

  for (const entry of entries) {
    const serverName = `${entry.subdomain}.${domain}`;
    lines.push(
      `server {`,
      `    listen 80;`,
      `    server_name ${serverName};`,
      ``,
      `    location / {`,
      `        proxy_pass http://${entry.serviceName}:${entry.port};`,
      `        proxy_set_header Host $host;`,
      `        proxy_set_header X-Real-IP $remote_addr;`,
      `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
      `        proxy_set_header X-Forwarded-Proto $scheme;`,
      `        proxy_http_version 1.1;`,
      `        proxy_set_header Upgrade $http_upgrade;`,
      `        proxy_set_header Connection "upgrade";`,
      `    }`,
      `}`,
      ``,
    );
  }

  return lines.join('\n');
}

/**
 * Write nginx config files — one per profile that has a domain configured.
 * Files are written to the same directory as the compose file.
 */
export function writeNginxConfigs(
  projectRoot: string,
  contracts: Map<string, ServiceContract>,
  profileNames: string[],
  profileSuffixes: Record<string, string>,
  profileDomains: Record<string, string>,
): NginxWriteResult[] {
  const results: NginxWriteResult[] = [];

  for (const profileName of profileNames) {
    const suffix = profileSuffixes[profileName] || '';
    const domain = profileDomains[profileName] || '';

    if (!domain) continue; // No domain configured, skip nginx for this profile

    const entries = collectNginxEntries(contracts, profileName, suffix, domain);

    if (entries.length === 0) continue;

    const content = generateNginxConfig(entries, domain, profileName);
    const fileName = profileNames.length === 1
      ? 'nginx.conf'
      : `nginx.${profileName}.conf`;
    const filePath = path.join(projectRoot, fileName);

    fs.writeFileSync(filePath, content, 'utf8');

    // Auto-gitignore the generated file (same pattern as compose)
    const gitignorePath = path.join(projectRoot, '.gitignore');
    if (fs.existsSync(gitignorePath)) {
      const gitignore = fs.readFileSync(gitignorePath, 'utf8');
      if (!gitignore.includes(fileName)) {
        fs.appendFileSync(gitignorePath, `\n${fileName}\n`);
      }
    }

    results.push({
      filePath,
      warnings: entries.map(e => `  ${e.subdomain}.${domain} → ${e.serviceName}:${e.port}`),
    });
  }

  return results;
}
