import * as fs from 'fs';
import * as path from 'path';
import type { ServiceContract } from '../contracts.js';
import { collectProxyEntries, type ProxyEntry } from './proxy-entries.js';

const GENERATED_HEADER = '# Generated by composable.env — DO NOT EDIT';

// Re-exports for backwards compatibility with existing imports
export type NginxServiceEntry = ProxyEntry;

export interface NginxWriteResult {
  filePath: string;
  warnings: string[];
}

/**
 * @deprecated Use collectProxyEntries from proxy-entries.js directly.
 * Kept for backwards compatibility; ignores profileName and profileDomain
 * (only profileSuffix affects entry collection).
 */
export function collectNginxEntries(
  contracts: Map<string, ServiceContract>,
  _profileName: string,
  profileSuffix: string,
  _profileDomain: string,
): NginxServiceEntry[] {
  return collectProxyEntries(contracts, profileSuffix);
}

/**
 * Generate nginx config content from entries for a specific profile.
 */
function generateNginxConfig(
  entries: ProxyEntry[],
  domain: string,
  profileName: string,
): string {
  const lines: string[] = [
    GENERATED_HEADER,
    `# Profile: ${profileName}`,
    '',
  ];

  for (const entry of entries) {
    const serverName = `${entry.subdomain}.${domain}`;
    lines.push(
      `server {`,
      `    listen 80;`,
      `    server_name ${serverName};`,
      ``,
      `    location / {`,
      `        proxy_pass http://${entry.serviceName}:${entry.port};`,
      `        proxy_set_header Host $host;`,
      `        proxy_set_header X-Real-IP $remote_addr;`,
      `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
      `        proxy_set_header X-Forwarded-Proto $scheme;`,
      `        proxy_http_version 1.1;`,
      `        proxy_set_header Upgrade $http_upgrade;`,
      `        proxy_set_header Connection "upgrade";`,
      `    }`,
      `}`,
      ``,
    );
  }

  return lines.join('\n');
}

/**
 * Write nginx config files — one per profile that has a domain configured.
 * Files are written to the same directory as the compose file.
 */
export function writeNginxConfigs(
  projectRoot: string,
  contracts: Map<string, ServiceContract>,
  profileNames: string[],
  profileSuffixes: Record<string, string>,
  profileDomains: Record<string, string>,
): NginxWriteResult[] {
  const results: NginxWriteResult[] = [];

  for (const profileName of profileNames) {
    const suffix = profileSuffixes[profileName] || '';
    const domain = profileDomains[profileName] || '';

    if (!domain) continue; // No domain configured, skip nginx for this profile

    const entries = collectProxyEntries(contracts, suffix);

    if (entries.length === 0) continue;

    const content = generateNginxConfig(entries, domain, profileName);
    const fileName = profileNames.length === 1
      ? 'nginx.conf'
      : `nginx.${profileName}.conf`;
    const filePath = path.join(projectRoot, fileName);

    fs.writeFileSync(filePath, content, 'utf8');

    // Auto-gitignore the generated file (same pattern as compose)
    const gitignorePath = path.join(projectRoot, '.gitignore');
    if (fs.existsSync(gitignorePath)) {
      const gitignore = fs.readFileSync(gitignorePath, 'utf8');
      if (!gitignore.includes(fileName)) {
        fs.appendFileSync(gitignorePath, `\n${fileName}\n`);
      }
    }

    results.push({
      filePath,
      warnings: entries.map(e => `  ${e.subdomain}.${domain} → ${e.serviceName}:${e.port}`),
    });
  }

  return results;
}
